name: Build VyOS LTS

# on: 
#   release:
#     types: [published]
#   push:
#     branches: 
#       - master
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

    - name: Pull vyos-build docker image
      run: |
        docker pull vyos/vyos-build:current
        
    - name: Build iso
      run: |
        git clone -b current --single-branch https://github.com/vyos/vyos-build.git
        cd vyos-build
        docker run --rm --privileged -v $(pwd):/vyos -w /vyos vyos/vyos-build:current bash -c './configure --architecture amd64 --build-type release --version "${{ env.RELEASE_VERSION }}" && sudo make iso'
   
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.myToken }}
        file: vyos-build/build/vyos-${{ env.RELEASE_VERSION }}-amd64.iso
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
  
  
