name: Build VyOS at Commit on Selfhosted
on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: Select the VyOS branch to build from
        options: 
        - equuleus
        - current
        - crux
      commit:
        description: SHA1 Commit

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, docker, x64]

    steps:

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date -u +'%Y%m%d%H%M')"

    - name: Decipher version number Crux
      if: contains(github.event.inputs.branch,'crux')
      run: echo "CODE_VERSION=1.2" >> $GITHUB_ENV

    - name: Decipher version number Equuleus
      if: contains(github.event.inputs.branch,'equuleus')
      run: echo "CODE_VERSION=1.3" >> $GITHUB_ENV

    - name: Decipher version number Sagitta
      if: contains(github.event.inputs.branch,'current')
      run: echo "CODE_VERSION=1.4" >> $GITHUB_ENV

    - name: Set release version
      run: echo "RELEASE_VERSION=${{ env.CODE_VERSION }}-${{ github.event.inputs.branch }}" >> $GITHUB_ENV

    - name: Pull vyos-build docker image
      run: docker pull vyos/vyos-build:${{ github.event.inputs.branch }}
        
    - name: Build iso
      run: |
        rm -rf vyos-build
        git clone -b ${{ github.event.inputs.branch }} https://github.com/vyos/vyos-build.git
        cd vyos-build
        git reset --hard ${{ github.event.inputs.commit }}
        export SHA1=$(git rev-parse --short HEAD)
        echo "COMMIT_ID=${SHA1}" >> $GITHUB_ENV
        export versioninfo="${{ env.RELEASE_VERSION }}-${SHA1}"
        docker run --rm --privileged -v $(pwd):/vyos -w /vyos vyos/vyos-build:${{ github.event.inputs.branch }} bash -c "./configure --architecture amd64 --build-type release --build-by Veduco --version ${versioninfo} && sudo make iso"
        ls -al 'build/'
   
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.myToken }}
        file: vyos-build/build/vyos-*.iso
        tag: ${{ env.RELEASE_VERSION }}-${{ env.COMMIT_ID }}
        overwrite: true
        file_glob: true
